version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8-stretch
      steps:
        - checkout
        - run: npm install -g npm
        - run: npm install --dev
        - run: npm run build
