version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.0
    steps:
      - checkout
      - run: npm install --dev
      - run: npm run build
      - run: npm run test:unit
      - run: npm run test:feature